SELECT USER
FROM DUAL;
--==>> HR

---■■■ 팀 별 실습 수행 과제 ■■■--
-- 20220304_02_hr(4팀_팀과제).sql

-- HR 샘플 스키마 ERD 를 이용한 테이블 재구성~!!!

-- 팀별로... HR 스키마에 있는 기본 테이블(7개)
-- COUNTRIES / DEPARTMENTS / EMPLOYEES / JOB_HISTORY / JOB / LOCATIONS / REGIONS
-- 을 똑~~~~~~~~같이 새로 구성한다.

-- 단, 생성하는 테이블 이름은 『테이블명+팀번호』
-- COUNTRIES1 / DEPARTMENTS1 / EMPLOYEES1 / JOB_HISTORY1 / JOB1 / LOCATIONS1 / REGIONS1
-- COUNTRIES2 / DEPARTMENTS2 / EMPLOYEES2 / JOB_HISTORY2 / JOB2 / LOCATIONS2 / REGIONS2
-- COUNTRIES3 / DEPARTMENTS3 / EMPLOYEES3 / JOB_HISTORY3 / JOB3 / LOCATIONS3 / REGIONS3
-- COUNTRIES4 / DEPARTMENTS4 / EMPLOYEES4 / JOB_HISTORY4 / JOB4 / LOCATIONS4 / REGIONS4
-- 와 같이 구성한다.

--1. 기존 대상 테이블들의 정보 수집
--2. 테이블 생성(컬럼이름, 자료형, DEFAULT 표현식, NOT NULL 등...)
--3. 제약조건 설정(PK, UK, FK, CK, ...)
--4. 작성 후 데이터 입력

-- 제출 항목
-- - 20220304_02_hr(1팀_팀과제).sql
-- - 20220304_02_hr(1팀_팀과제) 수행후기.txt

DESC LOCATIONS;

-- 테이블 생성 - COUNTRIES4의 COUNTRY_ID 컬럼을 참조하고 있다.
CREATE TABLE LOCATIONS4
(LOCATION_ID            NUMBER(4)   --4자리
,STREET_ADDRESS         VARCHAR(40) -- 50 Byte 가변 문자 (A = 1 Byte)
,POSTAL_CODE            VARCHAR(12) -- 12 Byte 가변 문자
,CITY                   VARCHAR(30) CONSTRAINT LOC4_LOC_CITY_NN NOT NULL
,STATE_PROVINCE         VARCHAR(25) -- 30 Byte 가변 문자
,COUNTRY_ID             CHAR(2)     -- 2 Byte 고정문자
,CONSTRAINT LOC4_LOC_ID_PK PRIMARY KEY(LOCATION_ID)
);


-- 제약조건 확인(제약조건 이름에는 4 붙이기)
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'LOCATIONS';
/*
HR	LOC_CITY_NN	LOCATIONS	C	CITY	"CITY" IS NOT NULL	
HR	LOC_ID_PK	LOCATIONS	P	LOCATION_ID		
HR	LOC_C_ID_FK	LOCATIONS	R	COUNTRY_ID		NO ACTION
*/


SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'LOCATIONS4';
-- 테이블 이름 / 컬럼명 / 데이터타입/ 제약조건(컨디션, 삭제룰, 참조)
/*
HR	LOC4_LOC_CITY_NN	LOCATIONS4	C	CITY	    "CITY" IS NOT NULL	
HR	LOC4_LOC_ID_PK	    LOCATIONS4	P	LOCATION_ID		
*/

--★★★제약조건 COUNTRIES4 참조(외래)★★★
ALTER TABLE LOCATIONS4
ADD(
 CONSTRAINT LOC4_LOC_C_ID_FK FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES4(COUNTRY_ID)
); 

-- 데이터 추가
INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1000,'1297 Via Cola di Rie','00989','Roma',NULL,'IT'); 

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1100,'93091 Calle della Testa','10934','Venice',NULL,'IT');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1200,'2017 Shinjuku-ku','1689','Tokyo','Tokyo Prefecture','JP');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1300,'9450 Kamiya-cho','6823','Hiroshima',NULL,'JP');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1400,'2014 Jabberwocky Rd','26192','Southlake','Texas','US');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1500,'2011 Interiors Blvd','99236','South San Francisco','California','US');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1600,'2007 Zagora St','50090','South Brunswick','New Jersey','US');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1700,'2004 Charade Rd','98199','Seattle','Washington','US');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1800,'147 Spadina Ave','M5V 2L7','Toronto','Ontario','CA');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1900,'6092 Boxwood St','YSW 9T2','Whitehorse','Yukon','CA');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2000,'40-5-12 Laogianggen','190518','Beijing',NULL,'CN');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2100,'1298 Vileparle (E)','490231','Bombay','Maharashtra','IN');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2200,'12-98 Victoria Street','2901','Sydney','New South Wales','AU');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2300,'198 Clementi North','540198','Singapore',NULL,'SG');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2400,'8204 Arthur St',NULL,'London',NULL,'UK');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2500,'Magdalen Centre, The Oxford Science Park','OX9 9ZB','Oxford','Oxford','UK');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2600,'9702 Chester Road','09629850293','Stretford','Manchester','UK');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2700,'Schwanthalerstr. 7031','80925','Munich','Bavaria','DE');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2800,'Rua Frei Caneca 1360','01307-002','Sao Paulo','Sao Paulo','BR');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2900,'20 Rue des Corps-Saints','1730','Geneva','Geneve','CH');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(3000,'Murtenstrasse 921','3095','Bern','BE','CH');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(3100,'Pieter Breughelstraat 837','3029SK','Utrecht','Utrecht','NL');

INSERT INTO LOCATIONS4(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(3200,'Mariano Escobedo 9991','11932','Mexico City','Distrito Federal,','MX');


--테이블 확인
SELECT *
FROM LOCATIONS4;

DROP TABLE LOCATIONS4;



--------------------------------------------------------------------------------




