SELECT USER
FROM DUAL;
--==>TEAM3 / 비밀번호 java006$



-- 이연주-----------------------------------------------------------------------

-- 교재
CREATE TABLE BOOK 
(
  BOOK_ID	VARCHAR2(10)	            -- 교재코드
, BOOK_NAME	VARCHAR2(30)	NOT NULL    -- 교재명
, BOOK_PUB	VARCHAR2(20)	NOT NULL        -- 출판사
, CONSTRAINT BOOK_BOOK_ID_PK PRIMARY KEY(BOOK_ID)  -- 제약조건
);
--코멘트
COMMENT ON TABLE BOOK IS '교재';
COMMENT ON COLUMN BOOK.BOOK_ID IS '교재코드';
COMMENT ON COLUMN BOOK.BOOK_NAME IS '교재명';
COMMENT ON COLUMN BOOK.BOOK_PUB IS '출판사';

-- 과목
CREATE TABLE SUBJECT 
(
  SUBJECT_ID	VARCHAR2(10)	            -- 과목코드
, SUBJECT_NAME	VARCHAR2(20)	NOT NULL        -- 과목명
, CONSTRAINT SUBJECT_SUJECT_ID_PK PRIMARY KEY(SUBJECT_ID)   -- 제약조건
);
--코멘트
COMMENT ON TABLE SUBJECT IS '과목';
COMMENT ON COLUMN BOOK.SUBJECT_ID IS '과목코드';
COMMENT ON COLUMN BOOK.SUBJECT_NAME IS '과목명';

/*
COMMENT ON TABLE [테이블명] IS [Comment];
COMMENT ON COLUMN [테이블명].[컬럼명] IS '[Comment]';
*/
-- 제약조건에는 NOT NULL이 들어가지 않음



--최문정------------------------------------------------------------------------
-- PROF (교수) 테이블 생성
CREATE TABLE PROF
( PROF_ID       VARCHAR2(10)
, PROF_NAME     VARCHAR2(20)    NOT NULL
, SSN           VARCHAR2(14)    NOT NULL
, PASSWORD      VARCHAR2(20)    NOT NULL 
, REGIST_DATE   DATE DEFAULT    SYSDATE
, CONSTRAINT PROF_PROF_ID_PK PRIMARY KEY(PROF_ID)
);

-- PROF (교수) 테이블의 컬럼 코멘트 입력
COMMENT ON COLUMN PROF.PROF_ID IS '교수ID';
COMMENT ON COLUMN PROF.PROF_NAME IS '교수이름';
COMMENT ON COLUMN PROF.SSN IS '주민등록번호';
COMMENT ON COLUMN PROF.PASSWORD IS '비밀번호';
COMMENT ON COLUMN PROF.REGIST_DATE IS '등록일';

-- COURSE (과정) 테이블 생성
CREATE TABLE COURSE 
( COURSE_ID     VARCHAR2(10)
, COURSE_NAME	VARCHAR2(20)    NOT NULL
, CONSTRAINT COURSE_COURSE_ID_PK PRIMARY KEY(COURSE_ID)
);

-- COURSE (과정) 테이블의 컬럼 코멘트 입력
COMMENT ON COLUMN COURSE.COURSE_ID IS '과정코드';
COMMENT ON COLUMN COURSE.COURSE_NAME IS '과정명';




-- 김민성-----------------------------------------------------------------------
--○ 학생테이블(STU) 생성
CREATE TABLE STU
( STU_ID       VARCHAR2(10)
, STU_NAME     VARCHAR2(20)
, SSN          VARCHAR2(14)
, PASSWORD     VARCHAR2(20) 
, REGIST_DATE  DATE  DEFAULT SYSDATE        
, CONSTRAINT STU_STU_ID_PK PRIMARY KEY(STU_ID)
);
-- 코멘트
COMMENT ON TABLE STU IS '학생정보테이블';
COMMENT ON TABLE STU.STU_ID IS '학생아이디';
COMMENT ON TABLE STU.STU_NAME IS '학생이름';
COMMENT ON TABLE STU.SSN IS '주민번호';
COMMENT ON TABLE STU.PASSWORD IS '비밀번호';
COMMENT ON TABLE STU.REGIST_DATE IS '등록일(기본값 SYSDATE)';


--○ 탈락사유(REASONS_DROPOUT) 테이블 생성
CREATE TABLE REASONS_DROPOUT
( REASONS_DROPOUT_ID    VARCHAR2(10)
, REASON_DROPOUT        VARCHAR2(40) 
, CONSTRAINT REASONS_DROPOUT_REASONS_DROPOUT_ID_PK PRIMARY KEY(REASONS_DROPOUT_ID)
);
-- 코멘트
COMMENT ON TABLE REASONS_DROPOUT IS '탈락사유테이블';
COMMENT ON TABLE REASONS_DROPOUT.REASONS_DROPOUT_ID IS '탈락사유코드';
COMMENT ON TABLE REASONS_DROPOUT.REASON_DROPOUT IS '탈락사유';



--김민성------------------------------------------------------------------------

-- ▼ 관리자 테이블, 제약조건, 코멘트
CREATE TABLE ADMIN
( ADMIN_ID      VARCHAR2(10)
, ADMIN_NAME    VARCHAR2(20)
, SSN           VARCHAR2(14)
, PASSWORD      VARCHAR2(20)
, REGIST_DATE   DATE DEFAULT SYSDATE

, CONSTRAINT    ADMIN_ADMIN_ID_PK       PRIMARY KEY(ADMIN_ID)
);

COMMENT ON TABLE ADMIN IS '관리자';
COMMENT ON COLUMN ADMIN.ADMIN_ID IS '관리자ID';
COMMENT ON COLUMN ADMIN.ADMIN_NAME IS '관리자명';
COMMENT ON COLUMN ADMIN.SSN IS '주민등록번호';
COMMENT ON COLUMN ADMIN.REGIST_DATE IS '등록일';


-- ▼ 강의실 테이블, 제약조건, 코멘트
CREATE TABLE CLASS
( CLASS_ID      VARCHAR2(10)
, CLASS_NAME    VARCHAR2(20)
, CONSTRAINT    CLASS_CLASS_ID_PK       PRIMARY KEY(CLASS_ID)
);

COMMENT ON TABLE CLASS IS '강의실';
COMMENT ON COLUMN CLASS.CLASS_ID IS '강의실코드';
COMMENT ON COLUMN CLASS.CLASS_NAME IS '강의실명';

